### ISSUE TITLE
Passing options to extensions

### ISSUE THREAD

**Issue by abegehr** [dmh126/react-adsk-forge-viewer-ts#1]
https://forge.autodesk.com/blog/viewer-extensions-tips-and-tricks-or-treats > Section: Passing options to extensions

I tried passing inputs to extensions like so:

```
<ForgeViewer
  local={true}
  path={url}
  extensions={[SelectedEntityExtension]}
  viewerOptions={{
    selectedEntityExtOptions: { msg: "boo!" },
  }}
/>
```

But in the extension `this.extOptions` stays empty.

The first option referenced in the docs linked above of using `viewer.loadExtension()` and passing the options there is not possible as far as I can tell since the extensions are loaded in the package's `useHooks()`

Is there something I'm missing for passing options to extensions?

**Comment by dmh126** [comment]
Hello @abegehr, you are right that property stays empty due to a small bug - extension initializes with its own property that doesn't exist. 
I published a fixed version, here is the PR: https://github.com/dmh126/react-adsk-forge-viewer-ts/pull/2
Now viewerOptions are passed as extOptions.

And the most current version of the package is 1.1.2.
https://www.npmjs.com/package/@contecht/react-adsk-forge-viewer/v/1.1.2

**Comment by abegehr** [comment]
Awesome, works 🙌
